name: 'publish'

on:
  push:
    tags:
      - '*'

env:
  HOME: $HOME:$HOME/.cargo/bin

jobs:
  init:
    name: Initialize project and build environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Install Rust and dependencies
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: List Rust files
        run: |
           ls -l $HOME/.cargo
      - name: Cache initialized setup
        uses: actions/cache/save@v4
        with:
          path: |
            ./*
            ./**
            /usr/lib/*
            $HOME/.cargo/*
            $HOME/.cargo/**
          key: ${{ runner.os }}-apicize-lib

  lint:
    name: Lint (Clippy)
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Restore initialized setup
        uses: actions/cache/restore@v4
        with:
          path: apicize-lib
          key: ${{ runner.os }}-apicize-lib
          fail-on-cache-miss: true
      - name: line lib-rust
        run: cargo clippy

  test:
    name: Unit testing
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Restore initialized setup
        uses: actions/cache/restore@v4
        with:
          path: apicize-lib
          key: ${{ runner.os }}-apicize-lib
          fail-on-cache-miss: true
      - name: line lib-rust
        run: cargo clippy
      

  publish-crate:
    name: Publish Crate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: 
      - 'lint'
      - 'test'
    steps:
      - name: Restore initialized setup
        uses: actions/cache/restore@v4
        with:
          path: apicize-lib
          key: ${{ runner.os }}-apicize-lib
          fail-on-cache-miss: true
      - name: Build the project
        run: cargo build --release
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish