name: 'publish'

on:
  push:
    tags:
      - '*'

jobs:
  lint:
    name: Lint (Clippy)
    runs-on: ubuntu-22.04
    steps:
      - name: checkout project
        uses: actions/checkout@v4
      - name: install rust and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: line lib-rust
        run: cargo clippy

  publish-crate:
    name: Publish Crate
    runs-on: Ubuntu-22.04
    permissions:
      contents: write
    needs: 'lint'
    steps:
      - name: checkout project
        uses: actions/checkout@v4
      - name: install rust and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: build dependencies
        run: cargo publish
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
